name: Release to Maven Central Repository
on:
    push:
        tags:
            - '*'

env:
    # Some forks are using older Java versions, so we need to maintain backward compatibility
    # or people's builds break, as the Maven Central version takes priority over local_lib
    # (not present anymore as of DV 6.0, but relevant for prior versions!). Result: hard code to Java 8.
    TARGET_JAVA_VERSION: 8

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Set up Java
              uses: actions/setup-java@v3
              with:
                  java-version: '17'
                  distribution: 'adopt'
            - name: Cache Maven packages
              uses: actions/cache@v3
              with:
                  path: ~/.m2
                  key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
                  restore-keys: ${{ runner.os }}-m2

            - name: Build, test, verify
              run: mvn -B verify -Djdk.version=${{ env.TARGET_JAVA_VERSION }}
            - name: Check POM metadata for release
              run: mvn pomchecker:check-maven-central

            # Running setup-java again overwrites the settings.xml - IT'S MANDATORY TO DO THIS SECOND SETUP!!!
            - name: Set up Maven Central Repository
              uses: actions/setup-java@v3
              with:
                  java-version: '17'
                  distribution: 'adopt'
                  server-id: ossrh
                  server-username: MAVEN_USERNAME
                  server-password: MAVEN_PASSWORD
                  gpg-private-key: ${{ secrets.DATAVERSEBOT_GPG_KEY }}
                  gpg-passphrase: MAVEN_GPG_PASSPHRASE
            - name: Sign + Publish release
              run: mvn -Prelease deploy -DskipAnalysis -DskipUT -DskipIT -Djdk.version=${{ env.TARGET_JAVA_VERSION }}
              env:
                  MAVEN_USERNAME: ${{ secrets.DATAVERSEBOT_SONATYPE_USERNAME }}
                  MAVEN_PASSWORD: ${{ secrets.DATAVERSEBOT_SONATYPE_TOKEN }}
                  MAVEN_GPG_PASSPHRASE: ${{ secrets.DATAVERSEBOT_GPG_PASSWORD }}